# SPDX-FileCopyrightText: 2021 Kaelan Thijs Fouwels <kaelan.thijs@fouwels.com>
#
# SPDX-License-Identifier: MIT
---
services:
  postgres:
    image: postgres:14.1-alpine3.15
    container_name: postgres
    environment:
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
      POSTGRES_DB: alfresco
    command: "
      postgres
      -c log_min_messages=WARNING
      -c log_directory=/dev/stdout
      -c max_connections=250"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: ${POSTGRES_MEMLIMIT}

volumes:
  postgres-data:

networks:
  postgres:
